#ifndef SPI_FLASH_CHIP_H
#define SPI_FLASH_CHIP_H

// Parameters for AT45DB081E

#define SPI_FLASH_CHIP_SZ 4096UL*256UL

#define SPI_FLASH_PAGE_ERASE_SZ 256UL
#define SPI_FLASH_BLOCK_ERASE_SZ 2048UL
#define SPI_FLASH_SECTOR_ERASE_SZ 65536UL

#endif // SPI_FLASH_CHIP_H
